---
- include: tasks/clear-history.yml
- include: tasks/docker.yml
- include: tasks/elixir.yml
- include: tasks/misc-packages.yml
- include: tasks/node.yml
- include: tasks/terraform.yml
- include: tasks/timezone.yml
- include: tasks/zsh-install.yml      # Needs a reboot to take effect

# Optional installs
# Reboot after you run these
# - include: tasks-optional/atom.yml
# - include: tasks-optional/google-chrome.yml
# - include: tasks-option/nylas-email.yml
# - include: tasks-optional/slack.yml
# - include: tasks-optional/spotify.yml
