---
- hosts: all
  become: true
  tasks:
    - name: add atom to apt repo
      apt_repository: repo={{ item }}
      with_items:
        - 'ppa:webupd8team/atom'
        - 'ppa:shutter/ppa'

    - name: update packages
      apt: update_cache=yes

    - name: install apt packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - atom
        - docker
        - docker-compose
        - nodejs
        - python-pip
        - ruby
        - shutter
        - terminator
        - tree
        - vim

    - name: install gems
      gem: name={{ item }} state=latest
      with_items:
        - bundler
        - lolcat

    - name: install pip packages
      pip: name={{ item }} state=latest
      with_items:
        - awscli
        - thefuck
        - virtualenv

    - name: copy vimrc
      template: src=../templates/vim/vimrc dest=~/.vimrc
