---
- hosts: all
  become: true
  tasks:
    - name: update packages
      apt: update_cache=yes

    - name: install apt packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - atom
        - docker
        - docker-compose
        - nodejs
        - python-pip
        - ruby
        - terminator
        - tree

    - name: install gems
      gem: name={{ item }} state=latest
      with_items:
        - bundler
        - lolcat

    - name: install pip packages
      pip: name={{ item }} state=latest
      with_items:
        - awscli
        - thefuck
        - virtualenv
