---
- hosts: all
  become: true
  tasks:
    - name: ensure terraform path exists
      file: path=/usr/local/terraform state=directory

    - name: download terraform zip
      get_url: url=https://releases.hashicorp.com/terraform/0.8.6/terraform_0.8.6_linux_amd64.zip dest=/tmp/terraform.zip mode=0644

    - name: install terraform
      unarchive: src=/tmp/terraform.zip dest=/usr/local/terraform
      become: true

    - name: remove terraform zip
      file: path=/tmp/terraform.zip state=absent
