---
- hosts: all
  become: true
  tasks:
    - name: download terraform zip
      get_url: url=https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_amd64.zip dest=/tmp/terraform.zip mode=0644

    - name: install terraform
      unarchive: src=/tmp/terraform.zip dest=/usr/local/terraform
      become: true
