---
- hosts: all
  become: true
  tasks:
    - name: Add the Spotify repository signing key to be able to verify downloaded packages
      apt_key: keyserver=keyserver.ubuntu.com id=BBEBDCB318AD50EC6865090613B00F1FD2C19886

    - name:  Add the Spotify repository
      apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present

    - name: Update packages
      apt: update_cache=yes

    - name: Install spotify
      apt: name=spotify-client state=present
