# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="{{ zsh_theme }}"

# plugins
plugins=( {% for plugin in zsh_plugins %}{{ plugin }} {% endfor %} )

source $ZSH/oh-my-zsh.sh

# path
export PATH=$PATH:/usr/local/terraform

# ssh
eval `ssh-agent -s`
ssh-add

# aliases
alias mv="mv -i"
alias grep="grep --color"
alias fuck='$(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
